spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/daou
    username: test
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql : true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: error
    #org.hibernate.type: trace
